version: '3.4'

services:

  post-db:
    image: library/postgres:9.6
    container_name: 'postgresPosts'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: post
    volumes:
      - post_data:/var/lib/postgresql/data

  user-db:
    image: library/postgres:9.6
    container_name: 'postgresUsers'
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - user_data:/var/lib/postgresql/data

  jibby-jabber:
    container_name: jibby-jabber
    image: docker.pkg.github.com/nickyfox/jibby-jabber/jibby-jabber-dev:latest
    ports:
      - '8080:8080'

  user-api:
    container_name: jibby-jabber-users
    image: docker.pkg.github.com/nickyfox/jibby-jabber-user/jibby-jabber-user-dev:latest
    ports:
      - '8082:8080'
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: users
      DB_HOST: postgresUsers
      DB_PORT: 5432

  posts-api:
    image: docker.pkg.github.com/agusllacuara/jibby-jabber-post/jibby-jabber-post-dev:latest
    ports:
      - '8083:8080'
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: post
      DB_HOST: postgresPosts
      DB_PORT: 5432

  client:
    container_name: jibby-jabber-client
    image: docker.pkg.github.com/agusllacuara/jibber-jabber-frontend/jj-frontend-image:latest


  revproxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    ports:
      - 80:80

volumes:
  user_data:
  post_data: