version: '3.4'

services:

  webmvc:
    image: jibby-jabber
    environment:
      - CatalogUrl=http://catalog-api
      - OrderingUrl=http://ordering-api
    ports:
      - "80:80"
    depends_on:
      - user-api
      - posts-api

  user-api:
    image: jibby-jabber-users
    environment:
      - ConnectionString=Server=sqldata;Port=1433;Database=CatalogDB;…
    ports:
      - "82:80"
    depends_on:
      - postgres

  posts-api:
    image: jibby-jabber-posts
    environment:
      - ConnectionString=Server=sqldata;Database=OrderingDb;…
    ports:
      -
      - "83:80"
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
      - "5433:5432"

