version: '3.4'

services:
  db:
    image: library/postgres:9.6
    container_name: 'postgresJibby'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgresJibby
    volumes:
      - db_data:/var/lib/postgresql/data

  jibby-jabber-dev:
    container_name: jibby-jabber-dev
    image: docker.pkg.github.com/nickyfox/jibby-jabber/jibby-jabber-dev:latest
    ports:
      - '8080:8080'
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: postgresJibby
      DB_HOST: postgresJibby
      DB_PORT: 5432

  user-api-dev:
    container_name: jibby-jabber-users-dev
    image: docker.pkg.github.com/nickyfox/jibby-jabber-user/jibby-jabber-user-dev:latest
    ports:
      - '8082:8080'
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: postgresJibby
      DB_HOST: postgresJibby
      DB_PORT: 5432

  posts-api-dev:
    container_name: jibby-jabber-posts-dev
    image: docker.pkg.github.com/agusllacuara/jibby-jabber-post/jibby-jabber-post-dev:latest
    ports:
      - '8083:8080'
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: postgresJibby
      DB_HOST: postgresJibby
      DB_PORT: 5432

  messages-api-dev:
    container_name: jibby-jabber-messages-dev
    image: docker.pkg.github.com/nickyfox/jibby-jabber-message/jibby-jabber-messages-dev:latest
    ports:
      - '8084:8080'
    environment:
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: postgresJibby
      DB_HOST: postgresJibby
      DB_PORT: 5432

  client-dev:
    container_name: jibby-jabber-client-dev
    image: docker.pkg.github.com/agusllacuara/jibber-jabber-frontend/jj-frontend-image-dev:latest

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

volumes:
  db_data:
